进化了

diff --git a/pmonitor b/pmonitor
--- a/pmonitor
+++ b/pmonitor
@@ -1,7 +1,7 @@
 #!/bin/bash
 pmonitor_file=/var/pmonitor/.pmonitor.me
 pmonitor_pid_file=/var/pmonitor/.pmonitor.pid
-
+platform=`uname`
 #define fun
 function is_process_exist(){
     pid=$1
@@ -14,35 +14,39 @@ function is_process_exist(){
 }
 
 function monitor(){
-while true
-do
-    while read line
+    while true
     do
-        commend=""
-        count=0
-        for token in $line
+        while read line
         do
-            if [ $count == 0 ];then
-                pid=$token
-                count=$count+1
-                continue
-            fi
-            if [ $count == 1 ];then
-                commend="$token"
-                continue
-            fi
-            commend="$commend $token"
-        done
+            commend=""
+            count=0
+            for token in $line
+            do
+                if [ $count == 0 ];then
+                    pid=$token
+                    count=$count+1
+                    continue
+                fi
+                if [ $count == 1 ];then
+                    commend="$token"
+                    continue
+                fi
+                commend="$commend $token"
+            done
 
-        is_process_exist $pid
-        if [ $? -eq 0 ];then
-            eval "$commend"
-            new_pid=$!
-            sed -i "s/${pid}/${new_pid}/g" $pmonitor_file
-        fi
-    done < $pmonitor_file
-    sleep 20
-done
+            is_process_exist $pid
+            if [ $? -eq 0 ];then
+                eval "$commend"
+                new_pid=$!
+                if [ "$platform" == "Darwin" ];then
+                    sed "" -i "s/${pid}/${new_pid}/g" $pmonitor_file
+                else
+                    sed -i "s/${pid}/${new_pid}/g" $pmonitor_file
+                fi
+            fi
+        done < $pmonitor_file
+        sleep 20
+    done
 }
 
 function runp(){
@@ -65,7 +69,11 @@ function runp(){
             echo "      only one process allow per program"
             exit
         fi
-        sed -i "/{$pid}/d" $pmonitor_file
+        if [ "$platform" == "Darwin" ];then
+            sed "" -i "/{$pid}/d" $pmonitor_file
+        else
+            sed -i "/{$pid}/d" $pmonitor_file
+        fi
     fi
 
     echo "running $run_commend"
@@ -74,34 +82,53 @@ function runp(){
     echo "$pid $run_commend" >> $pmonitor_file
 }
 
-if [ $# -lt 1 ];then
+function print_help(){
     echo "Usage:"
+    echo "       pmonitor install                 ---------- install pmonitor to system PATH"
     echo "       pmonitor monitor                 ---------- start monitor"
+    echo "       pmonitor stop                    ---------- stop monitor"
     echo "       pmonitor <program start commend> ---------- add program to monitor"
+}
+
+if [ $# -lt 1 ];then
+    echo "param number error!"
+    print_help
 fi
 
 if [ ! -d "/var/pmonitor" ];then
     mkdir /var/pmonitor
 fi
 
-if [ ! -f $pmonitor_pid_file ];then
-    eval "nohup pmonitor monitor &"
+function run_monitor(){
+    #run in ~
+    cd
+    eval "nohup pmonitor monitor_run &"
     pid=$!
     echo "$pid" > $pmonitor_pid_file
     touch $pmonitor_file
-else
-    read monitor_pid < $pmonitor_pid_file
-    is_process_exist $monitor_pid
-    if [ $? -eq 0 ];then
-        eval "nohup pmonitor monitor &"
-        pid=$!
-        echo "$pid" > $pmonitor_pid_file
-        touch $pmonitor_file
-    fi
-fi
+}
 
 if [ "$1" == "monitor" ];then
+    if [ ! -f $pmonitor_pid_file ];then
+        run_monitor
+    else
+        read monitor_pid < $pmonitor_pid_file
+        is_process_exist $monitor_pid
+        if [ $? -eq 0 ];then
+            run_monitor
+        fi
+    fi
+elif [ "$1" == "monitor_run" ];then
+    #do actually monitor
     monitor
+elif [ "$1" == "stop" ];then
+    read monitor_pid < $pmonitor_pid_file
+    kill $monitor_pid
+elif [ "$1" == "install" ];then
+    cp pmonitor /usr/local/bin/
+    echo "Install successfully!"
+elif [ "$1" == "-h" ];then
+    print_help
 else
     run_commend="nohup"
     for param in $*
